-- AlterTable
ALTER TABLE `Booking` ADD COLUMN `depositAmount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `depositPaid` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `fullAmount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `paymentStatus` VARCHAR(191) NOT NULL DEFAULT 'pending',
    ADD COLUMN `stripeSessionId` VARCHAR(191) NULL,
    MODIFY `clerkUserId` VARCHAR(191) NULL,
    MODIFY `numberOfGuests` INTEGER NOT NULL DEFAULT 10,
    MODIFY `status` VARCHAR(191) NOT NULL DEFAULT 'pending';
